os:
  - osx
  - linux
language: node_js
sudo: false
node_js:
  - "node"
  - "--lts"
notifications:
  email: false
install:
  - npm ci
script:
  - npm test
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
