os:
  - osx
  - linux
  - windows
dist: bionic
language: node_js
node_js:
  - "node"
  - "--lts"
notifications:
  email: false
cache: npm
install:
  - npm ci
script:
  - npm run lint
  - npm run test
after_success:
  - npx nyc report --reporter=text-lcov | npx coveralls
jobs:
  exclude:
    - node_js: "--lts"
      os: windows
