os:
  - osx
  - linux
  - windows
language: node_js
sudo: false
node_js:
  - "node"
  - "--lts"
notifications:
  email: false
cache: npm
install:
  - npm ci
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
